# Generated by Django 6.0.8 on 2026-09-09 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0002_shipment_shipmentpackage_shipmentitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(max_length=255)),
                ('evidence_media', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('item_received', 'Item Received'), ('restocked', 'Restocked'), ('written_off', 'Written Off'), ('closed', 'Closed')], db_index=True, default='requested', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Request (RMA)',
                'verbose_name_plural': 'Return Requests (RMAs)',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('tracking_number', models.CharField(db_index=True, max_length=128)),
                ('tracking_url', models.URLField(blank=True, default='')),
                ('label_url', models.URLField(blank=True, default='')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_shipments', to='shipping.carrier')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_shipment', to='orders.returnrequest')),
            ],
            options={
                'verbose_name': 'Return Shipment',
                'verbose_name_plural': 'Return Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
