# Generated by Django 6.0.8 on 2026-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_returnrequest_returnshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fulfilment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=30),
        ),
    ]
