# Generated by Django 6.0.8 on 2026-09-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('is_feature_flag', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.UUIDField(db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.UUIDField(null=True)),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='core_auditl_target__315580_idx'), models.Index(fields=['actor_id'], name='core_auditl_actor_i_870709_idx')],
            },
        ),
    ]
