# Generated by Django 6.0.8 on 2026-09-04 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('logo_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('rate_pct', models.DecimalField(decimal_places=2, help_text='Commission percentage, e.g. 15.00', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(blank=True, help_text='Null = platform-wide default rule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('account_holder', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=30)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('doc_type', models.CharField(choices=[('business_registration', 'Business Registration'), ('tax_certificate', 'Tax Certificate'), ('id_proof', 'ID Proof'), ('bank_statement', 'Bank Statement')], max_length=30)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('return_window_days', models.PositiveSmallIntegerField(default=30)),
                ('return_policy_text', models.TextField(blank=True)),
                ('shipping_policy_text', models.TextField(blank=True)),
                ('cancellation_policy_text', models.TextField(blank=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='vendors.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor policies',
            },
        ),
        migrations.CreateModel(
            name='VendorStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('staff_role', models.CharField(choices=[('manager', 'Manager'), ('support', 'Support'), ('fulfillment', 'Fulfillment')], default='support', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_staff_roles', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='vendors.vendor')),
            ],
            options={
                'ordering': ['staff_role', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='vendors_ven_status_2dcb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['slug'], name='vendors_ven_slug_6ed865_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorstaff',
            unique_together={('vendor', 'user')},
        ),
    ]
