# Generated by Django 6.0.8 on 2026-09-09 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_fulfilment_status'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('adjustments_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=20)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('external_transfer_id', models.CharField(blank=True, max_length=150)),
                ('ledger_entry_group_id', models.UUIDField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_line_items', to='orders.vendororder')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='vendors.vendorpayout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('post_release_refund', 'Post Release Refund'), ('penalty', 'Penalty'), ('correction', 'Correction')], max_length=50)),
                ('source_reference_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_adjustments', to='vendors.vendor')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='vendors.vendorpayout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorpayout',
            index=models.Index(fields=['vendor', 'period_start', 'period_end'], name='vendors_ven_vendor__4fac8e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayout',
            index=models.Index(fields=['status'], name='vendors_ven_status_64be95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payoutlineitem',
            unique_together={('payout', 'vendor_order')},
        ),
    ]
