# Generated by Django 6.0.8 on 2026-09-09 17:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(help_text='Unique identifier e.g. dhl, ups, usps, fedex, fake, vendor_self', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tracking_url_template', models.CharField(blank=True, default='', help_text='URL template with {tracking_number} placeholder', max_length=255)),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('countries', models.JSONField(default=list, help_text="List of ISO 2-letter uppercase country codes e.g. ['US', 'CA', 'GB']")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cart_or_order_ref', models.UUIDField(db_index=True, help_text='Cart ID or Order ID reference')),
                ('service_level', models.CharField(help_text='ground, express, overnight, white_glove', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('quote_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('estimated_days', models.PositiveIntegerField(default=3)),
                ('expires_at', models.DateTimeField()),
                ('redeemed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='shipping.carrier')),
            ],
            options={
                'verbose_name': 'Rate Quote',
                'verbose_name_plural': 'Rate Quotes',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('service_level', models.CharField(default='standard', help_text='e.g. standard, express, white_glove', max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_days', models.PositiveIntegerField(default=3)),
                ('max_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(blank=True, help_text='Null indicates platform standard rate card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rate_cards', to='vendors.vendor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Shipping Rate Card',
                'verbose_name_plural': 'Shipping Rate Cards',
                'ordering': ['base_rate'],
            },
        ),
        migrations.CreateModel(
            name='CarrierCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('credentials_encrypted', models.TextField(blank=True, default='', help_text='Encrypted JSON token/API key payload')),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='shipping.carrier')),
                ('vendor', models.ForeignKey(blank=True, help_text='Null indicates platform-wide master credential', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_credentials', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Carrier Credential',
                'verbose_name_plural': 'Carrier Credentials',
                'unique_together': {('carrier', 'vendor')},
            },
        ),
    ]
