# Generated by Django 6.0.8 on 2026-09-09 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0001_initial'),
        ('warehouse', '0002_inventoryreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('tracking_number', models.CharField(db_index=True, max_length=128)),
                ('tracking_url', models.URLField(blank=True, default='')),
                ('label_url', models.URLField(blank=True, default='')),
                ('label_format', models.CharField(default='PDF', max_length=20)),
                ('is_self_shipped', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('label_created', 'Label Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Failed Delivery Attempt'), ('exception', 'Delivery Exception'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='label_created', max_length=30)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.carrier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('rate_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.ratequote')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.vendororder')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('package_sequence', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=8)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Package',
                'verbose_name_plural': 'Shipment Packages',
                'ordering': ['package_sequence'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shipping.shipmentpackage')),
            ],
            options={
                'verbose_name': 'Shipment Item',
                'verbose_name_plural': 'Shipment Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('label_created', 'Label Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Failed Delivery Attempt'), ('exception', 'Delivery Exception'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=30)),
                ('carrier_status_code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Tracking Event',
                'verbose_name_plural': 'Shipment Tracking Events',
                'ordering': ['-event_timestamp'],
            },
        ),
    ]
