# Generated by Django 6.0.8 on 2026-09-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipment_shipmentpackage_shipmentitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('disabled', 'Disabled')], default='active', help_text='Operational status (active, coming_soon, disabled)', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='code',
            field=models.CharField(help_text='Unique identifier e.g. fedex, tcs, vendor_delivery, fake', max_length=50, unique=True),
        ),
    ]
