# Generated by Django 6.0.8 on 2026-09-09 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cart_item_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('order_item_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('COMMITTED', 'Committed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], db_index=True, default='HELD', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.inventory')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'expires_at'], name='warehouse_i_status_f691a2_idx')],
            },
        ),
    ]
