# Generated by Django 6.0.8 on 2026-09-09 17:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('authorize_net', 'Authorize.Net'), ('easypost', 'EasyPost / Shippo'), ('carrier_dhl', 'DHL Express'), ('carrier_ups', 'UPS'), ('carrier_usps', 'USPS'), ('carrier_fedex', 'FedEx')], db_index=True, max_length=30)),
                ('provider_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=30)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('authorize_net', 'Authorize.Net'), ('fake', 'FakeGateway (Sandbox)'), ('cod', 'Cash on Delivery')], default='fake', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('requires_action', 'Requires Action (3DS)'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=30)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_attempt_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Attempt',
                'verbose_name_plural': 'Payment Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('gateway', models.CharField(default='stripe', max_length=50)),
                ('gateway_payment_method_id', models.CharField(max_length=255)),
                ('gateway_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(default='Visa', max_length=30)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gateway_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('authorization', 'Authorization'), ('capture', 'Capture'), ('refund', 'Refund'), ('void', 'Void')], default='capture', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentattempt')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
