# Generated by Django 6.0.8 on 2026-09-09 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CODCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Collection'), ('otp_sent', 'OTP Sent to Customer'), ('collected', 'Collected & Verified'), ('failed', 'Collection Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('otp_code', models.CharField(blank=True, default='', max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cods', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cod_collection', to='orders.order')),
            ],
            options={
                'verbose_name': 'COD Collection',
                'verbose_name_plural': 'COD Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_vendor_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('held', 'Held'), ('eligible_for_release', 'Eligible For Release'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], db_index=True, default='held', max_length=30)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('eligible_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_holds', to='vendors.vendor')),
                ('vendor_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_hold', to='orders.vendororder')),
            ],
            options={
                'verbose_name': 'Escrow Hold',
                'verbose_name_plural': 'Escrow Holds',
                'ordering': ['-held_at'],
            },
        ),
    ]
