# Generated by Django 6.0.8 on 2026-09-09 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_returnrequest_returnshipment'),
        ('payments', '0002_codcollection_escrowhold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowhold',
            name='frozen_by_rma',
            field=models.ForeignKey(blank=True, help_text='Reference to open RMA freezing escrow release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_escrow_holds', to='orders.returnrequest'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('original_payment', 'Original Payment Method'), ('wallet', 'Store Credit Wallet'), ('manual', 'Manual Offline Refund')], db_index=True, default='original_payment', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('ledger_entry_group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('gateway_refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund', to='orders.returnrequest')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.vendororder')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
    ]
